### ISSUE TITLE
[Update] Carte pour le matchmaking

### ISSUE THREAD

**Issue by Sas226226** [KALrious/impact-bridge-front#52]
- [x] Sur les cartes il manque la fonctionnalité du « like »
Description: Le like va permettre que lorsqu'il y a un matchmaking de le confirmer, il va nous servir dans le sens ou certaines entités ne voudront communiquer qu'avec les autres entités qu'elles ont liké
- [x] Le fait qu’il soit online ou offline est à enlever
- [ ] Faire la connexion entre les cartes et les profils

**Comment by AntoineBourin** [comment]
Faire la connexion entre les cartes et les profils => quelle page ? elles s'affichent pas sur la page de search pour la recherche avancée c'est les cards verticales que je viens de faire donc je me demande sur quelle page pour celles-ci ?
